services:

  web:
    build: .
    volumes:
      - ./public:/app/public
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot:/etc/letsencrypt
      - ./nginx/www:/usr/share/nginx/html
    ports:
      - "8880:80"
      - "2053:443"
    depends_on:
      - web
    restart: always

  certbot:
    image: certbot/dns-cloudflare
    volumes:
      - ./nginx/certbot:/etc/letsencrypt
      - ./nginx/www:/usr/share/nginx/html
      - ./cloudflare.ini:/root/.secrets/cloudflare.ini
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CF_API_EMAIL=paitong1550@gmail.com
      - CF_API_KEY=f97fefab948554e23434b12f91f706b1a39ac
    command: certificates
    entrypoint: |
      /bin/sh -c 'apk add --no-cache docker-cli
      trap "exit 0" TERM
      while :; do
        certbot renew --dns-cloudflare --dns-cloudflare-credentials /root/.secrets/cloudflare.ini --preferred-challenges dns --quiet
        docker exec $$(docker ps -q -f name=nginx) nginx -s reload
        sleep 3d & wait $$!
      done'
    depends_on:
      - nginx

volumes:
  pgdata:
